version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=iwOIJqAzzD29
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=vovjai
